### ISSUE TITLE
기본 입력 방식 변경

### ISSUE THREAD

**Issue by kexplo** [kexplo/koach#2]
## 현안

파일을 인자로 받는다.

## 수정안

stdin을 기본으로 받고, 파일은 `-f` 옵션과 함께 받게 한다.

**Comment by sublee** [comment]
`cat`처럼 `-f` 옵션이 없는 게 더 관례적일 것 같습니다:

``` sh
$ cat /var/run/docker.pid
5932
$ echo 5932 | cat
5932
```

**Comment by kexplo** [comment]
`cat`처럼 쓰는 방향이 매우 좋은 것 같습니다.
